<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUftQxat\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUftQxat/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUftQxat.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUftQxat\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUftQxat\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UftQxat',
    'container.build_id' => 'fa83b284',
    'container.build_time' => 1521425689,
));
