<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2xLFm8b\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2xLFm8b/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2xLFm8b.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2xLFm8b\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2xLFm8b\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2xLFm8b',
    'container.build_id' => '23d9ee2f',
    'container.build_time' => 1520673738,
));
