<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbQwZ2q\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbQwZ2q/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXbQwZ2q.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXbQwZ2q\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXbQwZ2q\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XbQwZ2q',
    'container.build_id' => '7d433d77',
    'container.build_time' => 1520432803,
));
